### ISSUE TITLE
Will there be any macOS version

### ISSUE THREAD

**Issue by nathannewyen** [Elkosscom/poe_gwennen_gambler#6]

**Comment by mazei513** [comment]
Or linux.

**Comment by Elkosscom** [comment]
I've tried my luck with linux on VM, but no luck, unfortunately. I don't know enough about the system to do it. As for Mac OS, same thing. I am using pyinstaller (since it's the only tool I know to build a script into a file), but it only allows to build for the same system. If someone smarter than me can build it, would be great.
